import re
from pathlib import Path

import pytest
from playwright.sync_api import sync_playwright
from src.browser_print import install_print_suppression
from src.browser_window import set_main_window_bounds
from src.config_parser import Config


def _make_process_dpi_aware():
    try:
        import ctypes

        ctypes.windll.user32.SetProcessDPIAware()
    except Exception:
        pass


CHROMIUM_ARGS = [
    "--start-maximized",
    "--force-device-scale-factor=1",
    "--high-dpi-support=1",
    "--disable-popup-blocking",
]

FIREFOX_ARGS = []


def _download_launch_kwargs():
    download_dir = Path(Config.DOWNLOAD_DIR).expanduser()
    download_dir.mkdir(parents=True, exist_ok=True)
    return {"downloads_path": str(download_dir)}


def pytest_addoption(parser):
    parser.addoption(
        "--test-browser",
        action="store",
        default="chrome_port",
        help="Browser backend: edge, firefox, or chrome_port.",
    )
    parser.addoption(
        "--mapping-path",
        action="store",
        default="generated/valid/page_mapping.json",
        help="Mapping file generated by page_mapping.py.",
    )
    parser.addoption(
        "--risk-only",
        action="store_true",
        default=False,
        help="Run only High and Medium risk pages.",
    )
    parser.addoption(
        "--regression-limit",
        action="store",
        type=int,
        default=None,
        help="Limit the number of regression pages for smoke testing.",
    )
    parser.addoption(
        "--target-page",
        action="store",
        default=None,
        help="Run regression for one JSP filename, ignoring risk-level filtering.",
    )
    parser.addoption(
        "--target-pages",
        action="store",
        default=None,
        help="Run a JSP queue separated by commas, semicolons, or newlines.",
    )
    parser.addoption(
        "--manual",
        action="store_true",
        default=False,
        help="Enable manual takeover mode before automated regression continues.",
    )
    parser.addoption(
        "--login-entry",
        action="store",
        default=None,
        help="Login entry name or index; prompts when multiple .env entries exist.",
    )
    parser.addoption(
        "--struts-config",
        action="store",
        default="data/",
        help="Struts config file, directory, or comma-separated list.",
    )
    parser.addoption(
        "--checklist-path",
        action="store",
        default=None,
        help="Optional checklist xlsx; automation_mode=auto rows run first.",
    )
    parser.addoption(
        "--route-map-path",
        action="store",
        default=None,
        help="Optional usable_route_map JSON, directory, or glob path.",
    )
    parser.addoption(
        "--force-route-map",
        action="store_true",
        default=False,
        help="Prefer route-map navigation when a usable route map exists.",
    )
    parser.addoption(
        "--upload-file",
        action="store",
        default=None,
        help="Optional local file path used for automated upload controls.",
    )
    parser.addoption(
        "--upload-profile-config",
        action="store",
        default=None,
        help="Optional upload profile JSON generated by the GUI.",
    )
    parser.addoption(
        "--regression-output-dir",
        action="store",
        default=None,
        help="Optional output directory for screenshots and HTML reports.",
    )
    parser.addoption(
        "--include-semi-auto",
        action="store_true",
        default=False,
        help="Run checklist rows with automation_mode=semi-auto.",
    )
    parser.addoption(
        "--include-destructive",
        action="store_true",
        default=False,
        help="Run checklist rows with destructive=true.",
    )
    parser.addoption(
        "--include-negative",
        action="store_true",
        default=False,
        help="Run negative and error-injection cases; disabled by default.",
    )
    parser.addoption(
        "--negative-profile",
        action="store",
        default=None,
        help="Negative test profile name; comma-separated values are supported.",
    )
    parser.addoption(
        "--run-migration",
        action="store_true",
        default=False,
        help="Run migration regression tests that require a real browser login.",
    )


def pytest_runtest_setup(item):
    if item.name == "test_migration_regression" and not item.config.getoption("--run-migration"):
        pytest.skip("requires --run-migration with real browser/login environment")


@pytest.fixture(scope="session")
def browser_name(request):
    return request.config.getoption("--test-browser")


@pytest.fixture(scope="session")
def mapping_path(request):
    return request.config.getoption("--mapping-path")


@pytest.fixture(scope="session")
def risk_only(request):
    return request.config.getoption("--risk-only")


@pytest.fixture(scope="session")
def regression_limit(request):
    return request.config.getoption("--regression-limit")


@pytest.fixture(scope="session")
def target_page(request):
    return request.config.getoption("--target-page")


@pytest.fixture(scope="session")
def target_pages(request):
    raw_queue = request.config.getoption("--target-pages")
    if raw_queue:
        return [item.strip() for item in re.split(r"[\r\n,;]+", raw_queue) if item.strip()]
    single = request.config.getoption("--target-page")
    return [single.strip()] if single and single.strip() else []


@pytest.fixture(scope="session")
def manual(request):
    return request.config.getoption("--manual")


@pytest.fixture(scope="session")
def struts_config(request):
    return request.config.getoption("--struts-config")


@pytest.fixture(scope="session")
def route_map_path(request):
    return request.config.getoption("--route-map-path")


@pytest.fixture(scope="session")
def force_route_map(request):
    return request.config.getoption("--force-route-map")


@pytest.fixture(scope="session")
def upload_file(request):
    return request.config.getoption("--upload-file")


@pytest.fixture(scope="session")
def upload_profile_config(request):
    return request.config.getoption("--upload-profile-config")


@pytest.fixture(scope="session")
def regression_output_dir(request):
    return request.config.getoption("--regression-output-dir")


@pytest.fixture(scope="session")
def include_semi_auto(request):
    return request.config.getoption("--include-semi-auto")


@pytest.fixture(scope="session")
def include_destructive(request):
    return request.config.getoption("--include-destructive")


@pytest.fixture(scope="session")
def include_negative(request):
    return request.config.getoption("--include-negative")


@pytest.fixture(scope="session")
def negative_profile(request):
    return request.config.getoption("--negative-profile")


@pytest.fixture(scope="session")
def login_entry(request):
    return Config.select_login_entry(request.config.getoption("--login-entry"), interactive=True)


@pytest.fixture(scope="session")
def browser(browser_name, login_entry):
    _make_process_dpi_aware()
    with sync_playwright() as p:
        if browser_name == "edge":
            browser = p.chromium.launch(
                channel="msedge",
                headless=False,
                args=CHROMIUM_ARGS,
                **_download_launch_kwargs(),
            )
        elif browser_name == "firefox":
            browser = p.firefox.launch(
                headless=False,
                args=FIREFOX_ARGS,
                **_download_launch_kwargs(),
            )
        elif browser_name == "chrome_port":
            chrome_kwargs = {
                **Config.chrome_launch_kwargs(),
                **_download_launch_kwargs(),
                "headless": False,
                "args": [
                    "--start-maximized",
                    "--force-device-scale-factor=1",
                    "--high-dpi-support=1",
                    "--disable-popup-blocking",
                    "--disable-features=IsolateOrigins,site-per-process",
                    "--disable-site-isolation-trials",
                    "--disable-web-security",
                    "--allow-running-insecure-content",
                    "--no-sandbox",
                    "--disable-setuid-sandbox",
                    "--disable-dev-shm-usage",
                ],
            }
            browser = p.chromium.launch(**chrome_kwargs)
        else:
            raise ValueError(f"Unsupported browser backend: {browser_name}")

        yield browser
        browser.close()


def _authenticated_page(browser, base_url):
    context = browser.new_context(
        accept_downloads=True,
        no_viewport=True,
        user_agent="Moonlight-Automation-Agent",
    )
    install_print_suppression(context)

    def _safe_accept(dialog):
        try:
            dialog.accept()
        except Exception:
            pass

    context.on("dialog", _safe_accept)

    def _on_page(new_page):
        try:
            new_page.wait_for_load_state("domcontentloaded", timeout=10000)
        except Exception:
            pass

    context.on("page", _on_page)

    page = context.new_page()
    set_main_window_bounds(page)
    try:
        page.keyboard.press("Control+0")
        page.goto(base_url, wait_until="load", timeout=30000)
        page.keyboard.press("Control+0")
        page.fill("input[name='user']", Config.USERNAME)
        page.fill("input[name='password']", Config.PASSWORD)
        page.click("input[type='button']")
        page.wait_for_load_state("networkidle", timeout=30000)
        page.keyboard.press("Control+0")
    except Exception:
        pass
    return context, page


@pytest.fixture
def page_pair_factory(browser, login_entry):
    def factory():
        contexts = []
        legacy_context, legacy_page = _authenticated_page(browser, login_entry["legacy_url"])
        new_context, new_page = _authenticated_page(browser, login_entry["new_url"])
        contexts.extend([legacy_context, new_context])

        def close():
            for context in contexts:
                try:
                    context.close()
                except Exception:
                    pass

        return legacy_page, new_page, close

    return factory


@pytest.fixture(scope="session")
def legacy_page(browser, login_entry):
    context, page = _authenticated_page(browser, login_entry["legacy_url"])
    yield page
    context.close()


@pytest.fixture(scope="session")
def new_page(browser, login_entry):
    context, page = _authenticated_page(browser, login_entry["new_url"])
    yield page
    context.close()


@pytest.fixture(scope="session")
def page(new_page):
    """Compatibility fixture that returns an authenticated New-environment page."""
    yield new_page


def pytest_html_report_title(report):
    report.title = "Moonlight UI Regression Compatibility Report"


@pytest.fixture(scope="session")
def checklist_path(request):
    return request.config.getoption("--checklist-path")
